services:
    web:
        build:
            context: .
        command: make web
        ports:
            - "1282:1282"
        environment:
            - HF_TOKEN=${HF_TOKEN}  # Authenticate HF connection via local env var
        models:
            llm:
                endpoint_var: DOCKER_MODEL_RUNNER_ENDPOINT
                model_var: DOCKER_MODEL_RUNNER_LLM_NAME

models:
    llm:
        model: ai/gemma3-vllm:270M
