# -----------------------------------------------------------------
# Imports
# -----------------------------------------------------------------

import time
from typing import Dict, Optional

from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)
from encypher.core.keys import generate_ed25519_key_pair
from encypher.core.unicode_metadata import UnicodeMetadata

# -----------------------------------------------------------------
# Key Management
# -----------------------------------------------------------------

print(
    "\n======================== CREATING KEY PAIR =========================", end="\n\n"
)

# Generate a new Ed25519 key pair
private_key: Ed25519PrivateKey
public_key: Ed25519PublicKey
private_key, public_key = generate_ed25519_key_pair()
signer_id_manifest = "manifest-signer-001"

# Store public keys and create a provider function
public_keys_store: Dict[str, Ed25519PublicKey] = {signer_id_manifest: public_key}


def public_key_resolver(signer_id: str) -> Optional[Ed25519PublicKey]:
    return public_keys_store.get(signer_id)


# -----------------------------------------------------------------
# Create Text and Manifest
# -----------------------------------------------------------------

print(
    "\n======================== TEXT AND MANIFEST =========================", end="\n\n"
)

# Original text to be signed
original_text = "This is an important statement generated by an AI assistant."

# Embed a C2PA-inspired manifest
# The library automatically calculates the content hash of the original text.
c2pa_mainfest = {
    "metadata_format": "cbor_manifest",  # Use CBOR or jumbf manifest format
    "timestamp": int(time.time()),
    "claim_generator": "EncypherAI README Example v2.3",
    "actions": [
        {
            "action": "c2pa.created",
            "when": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "description": "Text was created by an AI model.",
        }
    ],
    "ai_info": {
        "model_id": "gpt-4o-2024-05-13",
        "prompt": "Write a short, important statement.",
    },
}

print(f"<< * >> Original text: '{original_text}'")
print(f"\n<< * >> C2PA manifest: '{c2pa_mainfest}'")

print(
    "\n======================== SIGNING PROCESS =========================", end="\n\n"
)

encoded_text_manifest = UnicodeMetadata.embed_metadata(
    text=original_text,
    private_key=private_key,
    signer_id=signer_id_manifest,
    **c2pa_mainfest,
)

print(f"\n<< * >> Text with embedded manifest: '{encoded_text_manifest}'")

# -----------------------------------------------------------------
# Verifying the Manifest and Detecting Tampering
# -----------------------------------------------------------------

# Verification confirms both the signature's authenticity and the text's integrity.
# Any change to the original text will cause verification to fail.

print(
    "\n======================== VERIFYING SIGNED TEXT =========================",
    end="\n\n",
)

# 1. Verify the original, unmodified text
is_valid, signer, payload = UnicodeMetadata.verify_metadata(
    text=encoded_text_manifest, public_key_resolver=public_key_resolver
)

print(f"\n<< * >> Verification of original text successful: {is_valid}")
if is_valid and payload:
    print(f"  - Signer ID: {signer}")
    print(f"  - ManifestPayload: {payload}")

print(
    "\n======================== VERIFYING MANIPULATED TEXT =========================",
    end="\n\n",
)

# 2. Attempt to verify tampered text
tampered_text = encoded_text_manifest.strip().replace(
    "generated by an AI ", "written by a human "
)
# tampered_text = "This is an important statement generated by an AI assistant."

is_tampered_valid, tampered_signer, tampered_payload = UnicodeMetadata.verify_metadata(
    text=tampered_text, public_key_resolver=public_key_resolver
)

print(f"\n<< * >> Manipulated text: '{tampered_text}'")
print(f"<< * >> Verification of tampered text successful: {is_tampered_valid}")

if is_tampered_valid and payload:
    print(f"  - Signer ID: {tampered_signer}")
    print(f"  - ManifestPayload: {tampered_payload}", end="\n\n")

else:
    print(
        "<< * >> Verification failed, indicating the text was tampered with.",
        end="\n\n",
    )
